run/output_directory/structure.rs: improve error messages
'Always' say the file name that can't be parsed. OTOH, do *not* tell
the parent path? Not sure about the latter (does not appear in the
tests).

But this resulting error is now good:

    Error: getting OutputSubdir listing for dir "/home/coworking/silo-benchmark-outputs/api/CONCURRENCY=120/DATASET=SC2open/RANDOMIZED=1/REPEAT=1/SORTED=0/45687eed8e8ac1d7904738f9f3d77e63729f7ea1"

    Caused by:
        dir name "CORRECT" does not parse as DateTimeWithOffset: input contains invalid characters